Repository S-KEEP/S-KEEP_Server, pull requests merged in 2024-07, with the labels that each got.

#23 (SKP-91) [Server] 엔티티를 설계한다
  src/main/java/Skeep/backend/category/domain/ECategory.java
  src/main/java/Skeep/backend/category/domain/FixedCategory.java
  src/main/java/Skeep/backend/category/domain/FixedCategoryRepository.java
  src/main/java/Skeep/backend/category/domain/UserCategory.java
  src/main/java/Skeep/backend/category/domain/UserCategoryRepository.java
  src/main/java/Skeep/backend/category/exception/CategoryErrorCode.java
  src/main/java/Skeep/backend/friend/domain/Friend.java
  src/main/java/Skeep/backend/friend/domain/FriendRepository.java
  src/main/java/Skeep/backend/location/domain/Location.java
  src/main/java/Skeep/backend/location/domain/LocationRepository.java
  src/main/java/Skeep/backend/location/domain/UserLocation.java
  src/main/java/Skeep/backend/location/domain/UserLocationRepository.java
  src/main/java/Skeep/backend/user/domain/User.java
Labels: :sparkles: feature

#24 (SKP-91) [Server] 엔티티를 설계한다
  src/main/java/Skeep/backend/category/domain/FixedCategoryRepository.java
  src/main/java/Skeep/backend/category/domain/UserCategoryRepository.java
  src/main/java/Skeep/backend/friend/domain/FriendRepository.java
  src/main/java/Skeep/backend/location/domain/LocationRepository.java
  src/main/java/Skeep/backend/location/domain/UserLocationRepository.java
  src/main/java/Skeep/backend/user/domain/UserRepository.java
Labels: :sparkles: feature

#26 (SKP-86) [Server] 애플 소셜 로그인을 구현한다
  build.gradle
  docs/S-KEEP에 애플 로그인 적용하기/SKEEP에 애플 로그인 적용하기.md
  docs/S-KEEP에 애플 로그인 적용하기/img.png
  docs/S-KEEP에 애플 로그인 적용하기/img_1.png
  docs/S-KEEP에 애플 로그인 적용하기/img_2.png
  docs/S-KEEP에 애플 로그인 적용하기/img_3.png
  docs/외부로 API 호출하기/외부로 API 호출하기.md
  src/main/java/Skeep/backend/BackendApplication.java
  src/main/java/Skeep/backend/auth/apple/controller/AppleController.java
  src/main/java/Skeep/backend/auth/apple/dto/AppleLoginRequest.java
  src/main/java/Skeep/backend/auth/apple/dto/ApplePublicKey.java
  src/main/java/Skeep/backend/auth/apple/dto/ApplePublicKeys.java
  src/main/java/Skeep/backend/auth/apple/service/AppleAuthClient.java
  src/main/java/Skeep/backend/auth/apple/service/ApplePublicKeyGenerator.java
  src/main/java/Skeep/backend/auth/apple/service/AppleService.java
  src/main/java/Skeep/backend/category/domain/ECategory.java
  src/main/java/Skeep/backend/category/domain/FixedCategory.java
  src/main/java/Skeep/backend/category/domain/UserCategory.java
  src/main/java/Skeep/backend/friend/domain/Friend.java
  src/main/java/Skeep/backend/global/security/config/SecurityConfig.java
  src/main/java/Skeep/backend/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/Skeep/backend/global/security/filter/JwtExceptionFilter.java
  src/main/java/Skeep/backend/global/security/handler/exception/CustomAccessDeniedHandler.java
  src/main/java/Skeep/backend/global/security/handler/exception/CustomAuthenticationEntryPointHandler.java
  src/main/java/Skeep/backend/global/security/handler/logout/CustomLogoutResultHandler.java
  src/main/java/Skeep/backend/global/security/info/AuthenticationResponse.java
  src/main/java/Skeep/backend/global/security/info/UserPrincipal.java
  src/main/java/Skeep/backend/global/security/provider/JwtAuthenticationManager.java
  src/main/java/Skeep/backend/global/security/provider/JwtAuthenticationProvider.java
  src/main/java/Skeep/backend/global/security/service/CustomUserDetailService.java
  src/main/java/Skeep/backend/global/util/HeaderUtil.java
  src/main/java/Skeep/backend/global/util/JwtUtil.java
  src/main/java/Skeep/backend/location/domain/Location.java
  src/main/java/Skeep/backend/location/domain/UserLocation.java
  src/main/java/Skeep/backend/user/domain/EProvider.java
  src/main/java/Skeep/backend/user/domain/EStatus.java
  src/main/java/Skeep/backend/user/domain/User.java
  src/main/java/Skeep/backend/user/domain/UserRepository.java
  src/main/java/Skeep/backend/user/exception/UserErrorCode.java
  src/main/java/Skeep/backend/user/service/UserFindService.java
  src/main/java/Skeep/backend/user/service/UserService.java
Labels: :sparkles: Feature

#46 (SKP-117) [Server] UserId 어노테이션을 통해서 인터셉터 단에서 로그인한 user id를 받아올 수 있다
  src/main/java/Skeep/backend/global/annotation/UserId.java
  src/main/java/Skeep/backend/global/config/WebConfig.java
  src/main/java/Skeep/backend/global/interceptor/post/ResponseInterceptor.java
  src/main/java/Skeep/backend/global/interceptor/pre/UserIdArgumentResolver.java
  src/main/java/Skeep/backend/global/interceptor/pre/UserIdInterceptor.java
Labels: :sparkles: Feature

#48 (SKP-118) [Server] @RequestParam을 @RequestBody로 변경한다
  src/main/java/Skeep/backend/auth/jwt/controller/TokenReissueApiController.java
Labels: 🔥 Bug

#51 지금까지 수정된 내용을 서버에 반영한다
  src/main/java/Skeep/backend/auth/jwt/controller/TokenReissueApiController.java
  src/main/java/Skeep/backend/global/annotation/UserId.java
  src/main/java/Skeep/backend/global/config/WebConfig.java
  src/main/java/Skeep/backend/global/interceptor/post/ResponseInterceptor.java
  src/main/java/Skeep/backend/global/interceptor/pre/UserIdArgumentResolver.java
  src/main/java/Skeep/backend/global/interceptor/pre/UserIdInterceptor.java
Labels: 🖥️ Deploy

#50 (SKP-106) [Server] 애플 로그아웃 및 회원 탈퇴를 구현하다
  build.gradle
  docs/SKEEP에 애플 로그인 적용하기/SKEEP에 애플 로그인 적용하기.md
  docs/SKEEP에 애플 로그인 적용하기/img.png
  docs/SKEEP에 애플 로그인 적용하기/img_1.png
  docs/SKEEP에 애플 로그인 적용하기/img_2.png
  docs/SKEEP에 애플 로그인 적용하기/img_3.png
  docs/SKEEP에 애플 탈퇴 적용하기/SKEEP에 애플 탈퇴 적용하기.md
  src/main/java/Skeep/backend/auth/apple/controller/AppleController.java
  src/main/java/Skeep/backend/auth/apple/dto/AppleAuthTokenResponse.java
  src/main/java/Skeep/backend/auth/apple/service/AppleOAuthManager.java
  src/main/java/Skeep/backend/auth/apple/service/AppleOAuthTokenClient.java
  src/main/java/Skeep/backend/auth/apple/service/ApplePublicKeyClient.java
  src/main/java/Skeep/backend/auth/apple/service/ApplePublicKeyGenerator.java
  src/main/java/Skeep/backend/auth/apple/service/AppleRevokeClient.java
  src/main/java/Skeep/backend/auth/apple/service/AppleService.java
  src/main/java/Skeep/backend/auth/exception/AuthErrorCode.java
  src/main/java/Skeep/backend/auth/jwt/controller/TokenReissueApiController.java
  src/main/java/Skeep/backend/auth/jwt/domain/RefreshTokenRepository.java
  src/main/java/Skeep/backend/auth/jwt/service/JwtTokenService.java
  src/main/java/Skeep/backend/global/constant/Constants.java
  src/main/java/Skeep/backend/global/security/config/SecurityConfig.java
  src/main/java/Skeep/backend/global/security/handler/logout/CustomLogoutProcessHandler.java
  src/main/java/Skeep/backend/global/security/handler/logout/CustomLogoutResultHandler.java
  src/main/java/Skeep/backend/global/util/HeaderUtil.java
  src/main/java/Skeep/backend/user/controller/UserController.java
  src/main/java/Skeep/backend/user/domain/User.java
  src/main/java/Skeep/backend/user/service/UserFindService.java
  src/main/java/Skeep/backend/user/service/UserService.java
  src/test/java/Skeep/backend/auth/jwt/controller/TokenReissueApiControllerTest.java
  src/test/java/Skeep/backend/auth/jwt/service/JwtTokenServiceTest.java
  src/test/java/Skeep/backend/fixture/TokenFixture.java
  src/test/java/Skeep/backend/global/ControllerTest.java
  src/test/java/Skeep/backend/global/security/handler/logout/CustomLogoutProcessHandlerTest.java
  src/test/java/Skeep/backend/global/util/JwtUtilTest.java
  src/test/resources/application.yml
Labels: :sparkles: Feature

#54 (SKP-119) [Server] 마이페이지 API를 구현한다
  src/main/java/Skeep/backend/user/controller/UserController.java
  src/main/java/Skeep/backend/user/dto/UserInformation.java
Labels: :sparkles: Feature

#56 [Server] Redis 연결이 되지 않는 문제를 해결한다
  src/main/java/Skeep/backend/global/config/RedisConfig.java
  src/test/resources/application.yml
Labels: 🔥 Bug

#57 지금까지 수정된 내용을 서버에 반영한다
  build.gradle
  docs/SKEEP에 애플 로그인 적용하기/SKEEP에 애플 로그인 적용하기.md
  docs/SKEEP에 애플 로그인 적용하기/img.png
  docs/SKEEP에 애플 로그인 적용하기/img_1.png
  docs/SKEEP에 애플 로그인 적용하기/img_2.png
  docs/SKEEP에 애플 로그인 적용하기/img_3.png
  docs/SKEEP에 애플 탈퇴 적용하기/SKEEP에 애플 탈퇴 적용하기.md
  src/main/java/Skeep/backend/auth/apple/controller/AppleController.java
  src/main/java/Skeep/backend/auth/apple/dto/AppleAuthTokenResponse.java
  src/main/java/Skeep/backend/auth/apple/service/AppleOAuthManager.java
  src/main/java/Skeep/backend/auth/apple/service/AppleOAuthTokenClient.java
  src/main/java/Skeep/backend/auth/apple/service/ApplePublicKeyClient.java
  src/main/java/Skeep/backend/auth/apple/service/ApplePublicKeyGenerator.java
  src/main/java/Skeep/backend/auth/apple/service/AppleRevokeClient.java
  src/main/java/Skeep/backend/auth/apple/service/AppleService.java
  src/main/java/Skeep/backend/auth/exception/AuthErrorCode.java
  src/main/java/Skeep/backend/auth/jwt/controller/TokenReissueApiController.java
  src/main/java/Skeep/backend/auth/jwt/domain/RefreshTokenRepository.java
  src/main/java/Skeep/backend/auth/jwt/service/JwtTokenService.java
  src/main/java/Skeep/backend/global/config/RedisConfig.java
  src/main/java/Skeep/backend/global/constant/Constants.java
  src/main/java/Skeep/backend/global/security/config/SecurityConfig.java
  src/main/java/Skeep/backend/global/security/handler/logout/CustomLogoutProcessHandler.java
  src/main/java/Skeep/backend/global/security/handler/logout/CustomLogoutResultHandler.java
  src/main/java/Skeep/backend/global/util/HeaderUtil.java
  src/main/java/Skeep/backend/user/controller/UserController.java
  src/main/java/Skeep/backend/user/domain/Email.java
  src/main/java/Skeep/backend/user/domain/User.java
  src/main/java/Skeep/backend/user/dto/UserInformation.java
  src/main/java/Skeep/backend/user/exception/UserErrorCode.java
  src/main/java/Skeep/backend/user/service/UserFindService.java
  src/main/java/Skeep/backend/user/service/UserService.java
  src/test/java/Skeep/backend/auth/jwt/controller/TokenReissueApiControllerTest.java
  src/test/java/Skeep/backend/auth/jwt/service/JwtTokenServiceTest.java
  src/test/java/Skeep/backend/category/domain/UserCategoryTest.java
  src/test/java/Skeep/backend/fixture/TokenFixture.java
  src/test/java/Skeep/backend/global/ControllerTest.java
  src/test/java/Skeep/backend/global/security/handler/logout/CustomLogoutProcessHandlerTest.java
  src/test/java/Skeep/backend/global/util/JwtUtilTest.java
  src/test/java/Skeep/backend/location/domain/UserLocationTest.java
  src/test/java/Skeep/backend/user/domain/UserRepositoryTest.java
  src/test/java/Skeep/backend/user/domain/UserTest.java
  src/test/java/Skeep/backend/user/service/UserServiceTest.java
  src/test/resources/application.yml
Labels: 🖥️ Deploy
