Repository S-KEEP/S-KEEP_Server, pull requests merged in 2024-09, with the labels that each got.

#138 (SKP-174) [Server] 날씨 조회 API에 주소를 Request로 추가한다
  src/main/java/Skeep/backend/global/ping/controller/PingController.java
  src/main/java/Skeep/backend/location/location/service/LocationRetriever.java
  src/main/java/Skeep/backend/weather/controller/WeatherController.java
  src/main/java/Skeep/backend/weather/exception/WeatherErrorCode.java
  src/main/java/Skeep/backend/weather/service/WeatherLocationService.java
  src/main/java/Skeep/backend/weather/service/WeatherSchedulerService.java
Labels: 🔥 Bug, 🔄 Refactor

#142 (SKP-177) [Server] 관광공사의 Items를 카카오맵에서 검증을 거치는 로직을 추가한다
  src/main/java/Skeep/backend/category/controller/UserCategoryController.java
  src/main/java/Skeep/backend/global/dto/CustomMultipartFile.java
  src/main/java/Skeep/backend/location/tour/service/TourService.java
  src/main/java/Skeep/backend/location/userLocation/controller/UserLocationController.java
  src/main/java/Skeep/backend/location/userLocation/domain/UserLocationRepository.java
  src/test/java/Skeep/backend/category/controller/UserCategoryControllerTest.java
Labels: 🔄 Refactor

#146 [Server] 명소 목록 조회 API에서 카테고리 반환을 추가한다
  build.gradle
  src/main/java/Skeep/backend/location/userLocation/controller/UserLocationController.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationListDto.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationService.java
Labels: :sparkles: Feature

#148 [Server] 친구 추가 토큰 API를 구현한다
  src/main/java/Skeep/backend/friend/contoller/FriendController.java
  src/main/java/Skeep/backend/friend/domain/Friend.java
  src/main/java/Skeep/backend/friend/dto/response/FriendTokenResponseDto.java
  src/main/java/Skeep/backend/friend/service/FriendSaver.java
  src/main/java/Skeep/backend/friend/service/FriendService.java
  src/main/java/Skeep/backend/location/userLocation/controller/UserLocationController.java
Labels: :sparkles: Feature

#150 [Server] 푸쉬 알림 API를 구현한다
  src/main/java/Skeep/backend/fcm/dto/response/FcmNotificationResponseDto.java
  src/main/java/Skeep/backend/fcm/exception/FcmErrorCode.java
  src/main/java/Skeep/backend/fcm/service/FcmService.java
  src/main/java/Skeep/backend/global/exception/GlobalErrorCode.java
  src/main/java/Skeep/backend/notification/controller/NotificationController.java
  src/main/java/Skeep/backend/notification/domain/BaseNotification/Notification.java
  src/main/java/Skeep/backend/notification/domain/BaseNotification/NotificationCustomRepository.java
  src/main/java/Skeep/backend/notification/domain/BaseNotification/NotificationCustomRepositoryImpl.java
  src/main/java/Skeep/backend/notification/domain/BaseNotification/NotificationProjection.java
  src/main/java/Skeep/backend/notification/domain/CategoryNotification/CategoryNotification.java
  src/main/java/Skeep/backend/notification/domain/CategoryNotification/CategoryNotificationRepository.java
  src/main/java/Skeep/backend/notification/domain/UserLocationNotification/UserLocationNotification.java
  src/main/java/Skeep/backend/notification/domain/UserLocationNotification/UserLocationNotificationRepository.java
  src/main/java/Skeep/backend/notification/dto/request/NotificationCheckRequestDto.java
  src/main/java/Skeep/backend/notification/dto/response/NotificationListResponseDto.java
  src/main/java/Skeep/backend/notification/dto/response/NotificationResponseDto.java
  src/main/java/Skeep/backend/notification/exception/CategoryNotificationErrorCode.java
  src/main/java/Skeep/backend/notification/exception/NotificationErrorCode.java
  src/main/java/Skeep/backend/notification/exception/UserLocationNotificationErrorCode.java
  src/main/java/Skeep/backend/notification/service/CategoryNotification/CategoryNotificationRetriever.java
  src/main/java/Skeep/backend/notification/service/CategoryNotification/CategoryNotificationUpdater.java
  src/main/java/Skeep/backend/notification/service/NotificationRetriever.java
  src/main/java/Skeep/backend/notification/service/NotificationService.java
  src/main/java/Skeep/backend/notification/service/NotificationUpdater.java
  src/main/java/Skeep/backend/notification/service/UserLocationNotification/UserLocationNotificationRetriever.java
  src/main/java/Skeep/backend/notification/service/UserLocationNotification/UserLocationNotificationUpdater.java
Labels: :sparkles: Feature

#159 (SKP-198) [Server] 회원 탈퇴 API 버그를 수정한다
  .gitignore
  src/main/java/Skeep/backend/category/controller/UserCategoryController.java
  src/main/java/Skeep/backend/category/service/UserCategoryRemover.java
  src/main/java/Skeep/backend/category/service/UserCategoryService.java
  src/main/java/Skeep/backend/friend/domain/FriendRepository.java
  src/main/java/Skeep/backend/friend/service/FriendRemover.java
  src/main/java/Skeep/backend/friend/service/FriendRetriever.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationRemover.java
  src/main/java/Skeep/backend/notification/domain/CategoryNotification/CategoryNotificationRepository.java
  src/main/java/Skeep/backend/notification/domain/UserLocationNotification/UserLocationNotificationRepository.java
  src/main/java/Skeep/backend/notification/service/NotificationRemover.java
  src/main/java/Skeep/backend/user/service/UserRemover.java
  src/main/java/Skeep/backend/user/service/UserWithdrawalService.java
  src/test/java/Skeep/backend/category/controller/UserCategoryControllerTest.java
  src/test/java/Skeep/backend/category/service/UserCategoryRemoverTest.java
  src/test/resources/skeep-fcm.json
Labels: 🔥 Bug

#160 (SKP-199) [Server] 심사를 위한 테스트 로그인 API 구현한다
  src/main/java/Skeep/backend/global/constant/Constants.java
  src/main/java/Skeep/backend/global/ping/controller/PingController.java
Labels: :sparkles: Feature

#161 (SKP-196) [Server] 이름이 한글일 경우, "성 + 이름"으로 변경한다
  src/main/java/Skeep/backend/auth/apple/service/AppleService.java
Labels: 🔄 Refactor

#162 [Server] 테스트 로그인 정상 응답으로 변경한다
  src/main/java/Skeep/backend/global/ping/controller/PingController.java
  src/main/java/Skeep/backend/user/domain/UserRepository.java
  src/main/java/Skeep/backend/user/service/UserFindService.java
Labels: 🔄 Refactor

#163 [Server] 카테고리 리마인드 푸쉬 알림 스케쥴링을 구현한다
  src/main/java/Skeep/backend/category/service/UserCategoryRetriever.java
  src/main/java/Skeep/backend/fcm/constant/FcmConstants.java
  src/main/java/Skeep/backend/fcm/constant/FcmContants.java
  src/main/java/Skeep/backend/fcm/dto/request/FcmTestRequestDto.java
  src/main/java/Skeep/backend/fcm/service/FcmService.java
  src/main/java/Skeep/backend/friend/service/FriendService.java
  src/main/java/Skeep/backend/global/config/AsyncConfig.java
  src/main/java/Skeep/backend/location/userLocation/controller/UserLocationController.java
  src/main/java/Skeep/backend/location/userLocation/domain/UserLocation.java
  src/main/java/Skeep/backend/location/userLocation/domain/UserLocationRepository.java
  src/main/java/Skeep/backend/location/userLocation/dto/request/FriendUserLocationCreateRequestDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/FriendUserLocationCreate.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationRetriever.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationService.java
  src/main/java/Skeep/backend/notification/service/NotificationRetriever.java
  src/main/java/Skeep/backend/notification/service/NotificationScheduleService.java
  src/main/java/Skeep/backend/notification/service/NotificationService.java
  src/main/java/Skeep/backend/notification/service/NotificationUpdater.java
  src/main/java/Skeep/backend/user/domain/UserRepository.java
  src/main/java/Skeep/backend/user/service/UserFindService.java
Labels: :sparkles: Feature

#166 (SKP-197) [Server] 추천 여행지 API를 구현한다
  src/main/java/Skeep/backend/friend/service/FriendRetriever.java
  src/main/java/Skeep/backend/global/constant/Constants.java
  src/main/java/Skeep/backend/global/ping/controller/PingController.java
  src/main/java/Skeep/backend/location/picks/controller/PicksController.java
  src/main/java/Skeep/backend/location/picks/domain/Picks.java
  src/main/java/Skeep/backend/location/picks/domain/PicksRepository.java
  src/main/java/Skeep/backend/location/picks/dto/request/PicksRequest.java
  src/main/java/Skeep/backend/location/picks/dto/response/PicksDto.java
  src/main/java/Skeep/backend/location/picks/dto/response/PicksDtoList.java
  src/main/java/Skeep/backend/location/picks/service/PicksService.java
  src/main/java/Skeep/backend/location/tour/controller/TourController.java
  src/main/java/Skeep/backend/location/tour/dto/response/TourLocationList.java
  src/main/java/Skeep/backend/notification/service/NotificationScheduleService.java
  src/main/java/Skeep/backend/s3/controller/S3Controller.java
  src/main/java/Skeep/backend/user/service/UserWithdrawalService.java
  src/main/java/Skeep/backend/weather/controller/WeatherController.java
  src/main/java/Skeep/backend/weather/service/WeatherLocationService.java
Labels: :sparkles: Feature

#167 (SKP-195) [Server] 날씨 업데이트를 스케쥴링하고 검증한다
  src/main/java/Skeep/backend/location/tour/service/TourService.java
  src/main/java/Skeep/backend/weather/controller/WeatherController.java
  src/main/java/Skeep/backend/weather/service/WeatherLocationService.java
  src/main/java/Skeep/backend/weather/service/WeatherSchedulerService.java
  src/main/java/Skeep/backend/weather/service/WeatherService.java
Labels: 🔄 Refactor

#169 (SKP-200) [Server] 테스트 로그인 시 500 에러 전송으로 변경한다
  src/main/java/Skeep/backend/global/ping/controller/PingController.java
Labels: 🔄 Refactor

#171 (SKP-201) [Server] application.yml 파일을 수정한다
  src/main/resources/application.yml
Labels: 🔄 Refactor

#173 (SKP-202) [Server] 에디터 추천 내 카테고리 추가 API 구현한다
  src/main/java/Skeep/backend/global/constant/Constants.java
  src/main/java/Skeep/backend/global/ping/controller/PingController.java
  src/main/java/Skeep/backend/location/picks/controller/PicksController.java
  src/main/java/Skeep/backend/location/picks/domain/PicksRepository.java
  src/main/java/Skeep/backend/location/picks/service/PicksService.java
Labels: :sparkles: Feature

#175 [Server] 테스트 푸시 API 수정 내용 서버 반영
  src/main/java/Skeep/backend/fcm/controller/FcmController.java
  src/main/java/Skeep/backend/fcm/service/FcmService.java
Labels: :sparkles: Feature

#176 [Server] 테스트 푸시 API 수정 내용 서버 반영
  src/main/java/Skeep/backend/fcm/controller/FcmController.java
  src/main/java/Skeep/backend/fcm/service/FcmService.java
Labels: 🖥️ Deploy
