Repository S-KEEP/S-KEEP_Server, pull requests merged in 2024-08, with the labels that each got.

#60 (SKP-112) [Server] Controller Test에 Response Body가 null인 문제를 해결하다
  src/main/java/Skeep/backend/auth/apple/controller/AppleController.java
  src/main/java/Skeep/backend/auth/jwt/controller/TokenReissueApiController.java
  src/main/java/Skeep/backend/kakaoMap/service/KakaoMapService.java
  src/main/java/Skeep/backend/screenshot/service/ScreenshotService.java
  src/test/java/Skeep/backend/auth/apple/controller/AppleControllerTest.java
  src/test/java/Skeep/backend/global/ControllerTest.java
  src/test/java/Skeep/backend/global/ServiceTest.java
  src/test/java/Skeep/backend/location/userLocation/domain/UserLocationTest.java
  src/test/resources/application.yml
Labels: 🔥 Bug

#66 (SKP-125) [Server] UserLocation API CRUD 구현
  src/main/java/Skeep/backend/category/domain/UserCategory.java
  src/main/java/Skeep/backend/category/domain/UserCategoryRepository.java
  src/main/java/Skeep/backend/category/service/UserCategorySaver.java
  src/main/java/Skeep/backend/location/userLocation/controller/UserLocationController.java
  src/main/java/Skeep/backend/location/userLocation/domain/UserLocation.java
  src/main/java/Skeep/backend/location/userLocation/domain/UserLocationRepository.java
  src/main/java/Skeep/backend/location/userLocation/dto/request/UserLocationGetDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/request/UserLocationPatchDto.java
  src/main/java/Skeep/backend/location/userLocation/exception/UserLocationErrorCode.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationRemover.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationRetriever.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationService.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationUpdater.java
  src/main/java/Skeep/backend/screenshot/service/ScreenshotService.java
Labels: :sparkles: Feature

#68 (SKP-126) [Server] GlobalAPIExceptionHandler와 BaseResponse를 연동한다
  src/main/java/Skeep/backend/global/base/BaseResponse.java
  src/main/java/Skeep/backend/global/interceptor/post/ResponseInterceptor.java
Labels: 🔥 Bug

#69 [Server] 지금까지의 변경 사항들을 모두 서버에 반영한다
  src/main/java/Skeep/backend/auth/apple/controller/AppleController.java
  src/main/java/Skeep/backend/auth/apple/service/AppleService.java
  src/main/java/Skeep/backend/auth/jwt/controller/TokenReissueApiController.java
  src/main/java/Skeep/backend/auth/jwt/service/JwtTokenService.java
  src/main/java/Skeep/backend/category/domain/UserCategory.java
  src/main/java/Skeep/backend/category/domain/UserCategoryRepository.java
  src/main/java/Skeep/backend/category/service/UserCategorySaver.java
  src/main/java/Skeep/backend/global/base/BaseResponse.java
  src/main/java/Skeep/backend/global/config/WebConfig.java
  src/main/java/Skeep/backend/global/constant/Constants.java
  src/main/java/Skeep/backend/global/interceptor/post/ResponseInterceptor.java
  src/main/java/Skeep/backend/global/security/config/SecurityConfig.java
  src/main/java/Skeep/backend/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/Skeep/backend/global/security/filter/JwtExceptionFilter.java
  src/main/java/Skeep/backend/global/security/handler/exception/CustomAccessDeniedHandler.java
  src/main/java/Skeep/backend/global/security/handler/exception/CustomAuthenticationEntryPointHandler.java
  src/main/java/Skeep/backend/global/security/handler/logout/CustomLogoutProcessHandler.java
  src/main/java/Skeep/backend/global/security/handler/logout/CustomLogoutResultHandler.java
  src/main/java/Skeep/backend/global/security/info/AuthenticationResponse.java
  src/main/java/Skeep/backend/global/security/info/JwtUserInfo.java
  src/main/java/Skeep/backend/global/security/info/UserPrincipal.java
  src/main/java/Skeep/backend/global/security/provider/JwtAuthenticationManager.java
  src/main/java/Skeep/backend/global/security/provider/JwtAuthenticationProvider.java
  src/main/java/Skeep/backend/global/security/service/CustomUserDetailService.java
  src/main/java/Skeep/backend/global/util/JwtUtil.java
  src/main/java/Skeep/backend/gpt/service/GptService.java
  src/main/java/Skeep/backend/kakaoMap/service/KakaoMapService.java
  src/main/java/Skeep/backend/location/location/service/LocationRetriever.java
  src/main/java/Skeep/backend/location/location/service/LocationSaver.java
  src/main/java/Skeep/backend/location/location/service/LocationService.java
  src/main/java/Skeep/backend/location/userLocation/controller/UserLocationController.java
  src/main/java/Skeep/backend/location/userLocation/domain/UserLocation.java
  src/main/java/Skeep/backend/location/userLocation/domain/UserLocationRepository.java
  src/main/java/Skeep/backend/location/userLocation/dto/request/FixedCategoryDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/request/UserLocationGetDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/request/UserLocationPatchDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/LocationDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserCategoryDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationListDto.java
  src/main/java/Skeep/backend/location/userLocation/exception/UserLocationErrorCode.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationRemover.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationRetriever.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationService.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationUpdater.java
  src/main/java/Skeep/backend/screenshot/service/ScreenshotService.java
  src/main/java/Skeep/backend/user/domain/ERole.java
  src/main/java/Skeep/backend/user/domain/User.java
  src/main/java/Skeep/backend/user/domain/UserRepository.java
  src/main/java/Skeep/backend/user/dto/UserSecurityForm.java
  src/main/java/Skeep/backend/user/service/UserFindService.java
  src/main/java/Skeep/backend/user/service/UserService.java
  src/test/java/Skeep/backend/auth/apple/controller/AppleControllerTest.java
  src/test/java/Skeep/backend/auth/jwt/service/JwtTokenServiceTest.java
  src/test/java/Skeep/backend/global/ControllerTest.java
  src/test/java/Skeep/backend/global/ServiceTest.java
  src/test/java/Skeep/backend/global/util/JwtUtilTest.java
  src/test/java/Skeep/backend/location/userLocation/domain/UserLocationTest.java
  src/test/resources/application.yml
Labels: 🖥️ Deploy

#70 (SKP-107) [Server] 카테고리 추가 및 목록 조회 API를 구현한다
  src/main/java/Skeep/backend/auth/apple/service/AppleService.java
  src/main/java/Skeep/backend/auth/exception/AuthErrorCode.java
  src/main/java/Skeep/backend/auth/jwt/controller/TokenReissueApiController.java
  src/main/java/Skeep/backend/auth/jwt/dto/NewAccessTokenResponse.java
  src/main/java/Skeep/backend/auth/jwt/dto/RefreshTokenRequest.java
  src/main/java/Skeep/backend/auth/jwt/service/JwtTokenService.java
  src/main/java/Skeep/backend/category/controller/UserCategoryController.java
  src/main/java/Skeep/backend/category/domain/UserCategory.java
  src/main/java/Skeep/backend/category/domain/UserCategoryRepository.java
  src/main/java/Skeep/backend/category/dto/UserCategoryList.java
  src/main/java/Skeep/backend/category/service/UserCategoryService.java
  src/main/java/Skeep/backend/global/security/config/SecurityConfig.java
  src/main/java/Skeep/backend/screenshot/service/ScreenshotService.java
  src/test/java/Skeep/backend/auth/apple/controller/AppleControllerTest.java
  src/test/java/Skeep/backend/auth/jwt/controller/TokenReissueApiControllerTest.java
  src/test/java/Skeep/backend/category/controller/UserCategoryControllerTest.java
  src/test/java/Skeep/backend/category/domain/UserCategoryRepositoryTest.java
  src/test/java/Skeep/backend/category/domain/UserCategoryTest.java
  src/test/java/Skeep/backend/category/service/UserCategoryServiceTest.java
  src/test/java/Skeep/backend/fixture/UserCategoryFixture.java
  src/test/java/Skeep/backend/fixture/UserFixture.java
  src/test/java/Skeep/backend/global/ControllerTest.java
  src/test/java/Skeep/backend/global/ServiceTest.java
  src/test/java/Skeep/backend/location/userLocation/domain/UserLocationTest.java
  src/test/java/Skeep/backend/user/controller/UserControllerTest.java
  src/test/java/Skeep/backend/user/domain/UserRepositoryTest.java
  src/test/java/Skeep/backend/user/domain/UserTest.java
Labels: :sparkles: Feature

#76 (SKP-129) [Server] 동작하지 않는 테스트를 바로 잡는다
  src/main/java/Skeep/backend/auth/apple/service/AppleService.java
  src/main/java/Skeep/backend/category/domain/UserCategory.java
  src/main/java/Skeep/backend/global/security/config/SecurityConfig.java
  src/main/java/Skeep/backend/location/userLocation/domain/UserLocation.java
  src/test/java/Skeep/backend/auth/apple/controller/AppleControllerTest.java
  src/test/java/Skeep/backend/auth/jwt/controller/TokenReissueApiControllerTest.java
  src/test/java/Skeep/backend/category/controller/UserCategoryControllerTest.java
  src/test/java/Skeep/backend/global/ControllerTest.java
  src/test/java/Skeep/backend/location/userLocation/domain/UserLocationTest.java
  src/test/java/Skeep/backend/user/controller/UserControllerTest.java
Labels: ✅ Test

#77 (SKP-120) [Server] Apple 연동 해제 API에 대한 테스트 코드를 작성한다
  docs/SKEEP에 애플 탈퇴 적용하기/SKEEP에 애플 탈퇴 적용하기.md
  src/main/java/Skeep/backend/auth/apple/service/AppleOAuthManager.java
  src/main/java/Skeep/backend/global/constant/Constants.java
  src/main/java/Skeep/backend/global/exception/ApiGlobalExceptionHandler.java
Labels: ✅ Test

#81 (SKP-131) [Server] 애플 시리얼 아이디로 로그인 API를 생성한다
  src/main/java/Skeep/backend/global/constant/Constants.java
  src/main/java/Skeep/backend/global/ping/controller/PingController.java
Labels: :sparkles: Feature

#85 (SKP-136) [Server] 프론트엔드 요청 사항을 서버에 반영한다
  src/main/java/Skeep/backend/location/userLocation/controller/UserLocationController.java
  src/main/java/Skeep/backend/location/userLocation/domain/UserLocationRepository.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationListDto.java
  src/main/java/Skeep/backend/location/userLocation/exception/UserLocationErrorCode.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationRetriever.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationService.java
Labels: 🖥️ Deploy

#88 [Server] 명소 생성 시, Response Body를 반환한다
  src/main/java/Skeep/backend/location/userLocation/controller/UserLocationController.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationCreate.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationCreateDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationDto.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationService.java
Labels: :sparkles: Feature

#89 [Server] 명소 생성 API 수정 사항 반영
  src/main/java/Skeep/backend/location/userLocation/controller/UserLocationController.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationCreate.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationCreateDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationDto.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationService.java
Labels: 🖥️ Deploy

#90 (SKP-132) [Server] 각 Category에 대한 Description을 확정한다
  src/main/java/Skeep/backend/category/domain/ECategory.java
  src/main/java/Skeep/backend/category/domain/UserCategoryRepository.java
  src/main/java/Skeep/backend/category/service/UserCategorySaver.java
  src/main/java/Skeep/backend/global/ping/controller/PingController.java
  src/test/java/Skeep/backend/category/domain/UserCategoryRepositoryTest.java
  src/test/java/Skeep/backend/category/service/UserCategorySaverTest.java
Labels: 🔄 Refactor, ✅ Test

#91 (SKP-137) [Server] 명소 관련 API 코드들을 refactoring 한다.
  src/main/java/Skeep/backend/gpt/service/GptService.java
  src/main/java/Skeep/backend/location/userLocation/controller/UserLocationController.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/LocationDto.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserCategoryDto.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationService.java
Labels: 🔄 Refactor

#96 (SKP-140) [Server] 명소 정보 API에서 도로명 주소를 반환한다
  src/main/java/Skeep/backend/kakaoMap/dto/response/KakaoResponseResult.java
  src/main/java/Skeep/backend/kakaoMap/service/KakaoMapService.java
  src/main/java/Skeep/backend/location/location/domain/Location.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/LocationDto.java
  src/main/java/Skeep/backend/screenshot/service/ScreenshotService.java
  src/test/java/Skeep/backend/location/userLocation/domain/UserLocationTest.java
Labels: :sparkles: Feature

#97 [Server] 명소 정보 API를 서버에 반영한다
  src/main/java/Skeep/backend/kakaoMap/dto/response/KakaoResponseResult.java
  src/main/java/Skeep/backend/kakaoMap/service/KakaoMapService.java
  src/main/java/Skeep/backend/location/location/domain/Location.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/LocationDto.java
  src/main/java/Skeep/backend/screenshot/service/ScreenshotService.java
  src/test/java/Skeep/backend/location/userLocation/domain/UserLocationTest.java
Labels: 🖥️ Deploy

#98 (SKP-124) [Server] 회원탈퇴 7일이 지난 사용자를 데이터베이스에서 삭제한다
  src/main/java/Skeep/backend/BackendApplication.java
  src/main/java/Skeep/backend/category/domain/ECategory.java
  src/main/java/Skeep/backend/category/domain/UserCategory.java
  src/main/java/Skeep/backend/category/domain/UserCategoryRepository.java
  src/main/java/Skeep/backend/global/base/BaseTimeEntity.java
  src/main/java/Skeep/backend/location/userLocation/domain/UserLocationRepository.java
  src/main/java/Skeep/backend/user/domain/UserRepository.java
  src/main/java/Skeep/backend/user/service/UserWithdrawalService.java
  src/test/java/Skeep/backend/category/controller/UserCategoryControllerTest.java
  src/test/java/Skeep/backend/category/domain/UserCategoryRepositoryTest.java
  src/test/java/Skeep/backend/fixture/LocationFixture.java
  src/test/java/Skeep/backend/fixture/UserCategoryFixture.java
  src/test/java/Skeep/backend/location/userLocation/domain/UserLocationRepositoryTest.java
  src/test/java/Skeep/backend/user/domain/UserRepositoryTest.java
Labels: :sparkles: Feature

#100 (SKP-142) [Server] 명소 API에 장소 이름을 추가한다
  src/main/java/Skeep/backend/kakaoMap/dto/response/KakaoResponseResult.java
  src/main/java/Skeep/backend/kakaoMap/service/KakaoMapService.java
  src/main/java/Skeep/backend/location/location/domain/Location.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/LocationDto.java
  src/main/java/Skeep/backend/screenshot/service/ScreenshotService.java
Labels: :sparkles: Feature

#108 (SKP-150) [Server] 회원 탈퇴시 데이터베이스에서 관련 데이터를 즉시 지운다
  src/main/java/Skeep/backend/user/controller/UserController.java
  src/main/java/Skeep/backend/user/service/UserService.java
  src/main/java/Skeep/backend/user/service/UserWithdrawalService.java
  src/test/java/Skeep/backend/global/ControllerTest.java
  src/test/java/Skeep/backend/global/ServiceTest.java
  src/test/java/Skeep/backend/user/controller/UserControllerTest.java
  src/test/java/Skeep/backend/user/service/UserWithdrawalServiceTest.java
Labels: 🔄 Refactor

#110 (SKP-151) [Server] '익사이팅'을 '액티비티'로 변경한다
  src/main/java/Skeep/backend/category/domain/ECategory.java
  src/main/java/Skeep/backend/user/controller/UserController.java
  src/main/java/Skeep/backend/user/service/UserService.java
  src/main/java/Skeep/backend/user/service/UserWithdrawalService.java
  src/test/java/Skeep/backend/category/controller/UserCategoryControllerTest.java
  src/test/java/Skeep/backend/category/domain/UserCategoryRepositoryTest.java
  src/test/java/Skeep/backend/category/service/UserCategoryServiceTest.java
  src/test/java/Skeep/backend/fixture/LocationFixture.java
  src/test/java/Skeep/backend/fixture/UserCategoryFixture.java
  src/test/java/Skeep/backend/location/location/domain/LocationTest.java
  src/test/java/Skeep/backend/location/userLocation/domain/UserLocationRepositoryTest.java
  src/test/java/Skeep/backend/location/userLocation/domain/UserLocationTest.java
  src/test/java/Skeep/backend/user/service/UserWithdrawalServiceTest.java
Labels: 🔄 Refactor

#113 (SKP-154) [Server] 프론트 요청 사항 및 Ecategory 수정을 한다
  src/main/java/Skeep/backend/category/domain/ECategory.java
  src/main/java/Skeep/backend/kakaoMap/service/KakaoMapService.java
  src/main/java/Skeep/backend/location/userLocation/dto/response/UserLocationListDto.java
  src/main/java/Skeep/backend/location/userLocation/exception/UserLocationErrorCode.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationService.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationTransactionalService.java
  src/main/java/Skeep/backend/screenshot/service/ScreenshotService.java
Labels: 🔥 Bug

#122 (SKP-158) [Server] 카테고리 생성 API를 구현한다
  src/main/java/Skeep/backend/category/controller/UserCategoryController.java
  src/main/java/Skeep/backend/category/dto/request/UserCategoryCreateRequest.java
  src/main/java/Skeep/backend/category/service/UserCategorySaver.java
  src/main/java/Skeep/backend/global/exception/GlobalErrorCode.java
  src/test/java/Skeep/backend/category/controller/UserCategoryControllerTest.java
  src/test/java/Skeep/backend/category/domain/UserCategoryRepositoryTest.java
  src/test/java/Skeep/backend/category/service/UserCategorySaverTest.java
Labels: :sparkles: Feature

#123 (SKP-159) [Server] 한국관광공사의 관광지 추천 API를 구현한다
  build.gradle
  src/main/java/Skeep/backend/global/config/WebConfig.java
  src/main/java/Skeep/backend/location/location/service/LocationRetriever.java
  src/main/java/Skeep/backend/location/location/service/LocationSaver.java
  src/main/java/Skeep/backend/location/location/service/LocationService.java
  src/main/java/Skeep/backend/location/tour/controller/TourController.java
  src/main/java/Skeep/backend/location/tour/dto/request/TourLocationRequest.java
  src/main/java/Skeep/backend/location/tour/dto/response/TourLocationList.java
  src/main/java/Skeep/backend/location/tour/dto/response/TourLocationResponse.java
  src/main/java/Skeep/backend/location/tour/exception/TourErrorCode.java
  src/main/java/Skeep/backend/location/tour/service/KoreanTourInfoService.java
  src/main/java/Skeep/backend/location/tour/service/TourService.java
  src/main/java/Skeep/backend/location/userLocation/service/UserLocationRetriever.java
  src/main/java/Skeep/backend/tour/service/TourService.java
Labels: :sparkles: Feature

#130 (SKP-170) [Server] 모든 Location에 대하여 Weather을 생성하는 로직을 구현한다
  src/main/java/Skeep/backend/global/ping/controller/PingController.java
  src/main/java/Skeep/backend/weather/domain/EWeatherCondition.java
  src/main/java/Skeep/backend/weather/domain/Weather.java
  src/main/java/Skeep/backend/weather/domain/WeatherRepository.java
  src/main/java/Skeep/backend/weather/domain/locationGrid/LocationGrid.java
  src/main/java/Skeep/backend/weather/domain/locationGrid/LocationGridRepository.java
  src/main/java/Skeep/backend/weather/dto/response/WeatherRequest.java
  src/main/java/Skeep/backend/weather/exception/WeatherErrorCode.java
  src/main/java/Skeep/backend/weather/service/WeatherRetriever.java
  src/main/java/Skeep/backend/weather/service/WeatherSchedulerService.java
  src/main/java/Skeep/backend/weather/service/WeatherService.java
  src/main/java/Skeep/backend/weather/service/locationGrid/LocationGridService.java
  src/main/java/Skeep/backend/weather/util/RegionUtils.java
  src/main/resources/weather/ddl-grid-converter.sql
  src/main/resources/weather/dml-grid-converter.sql
  src/test/java/Skeep/backend/category/domain/UserCategoryRepositoryTest.java
  src/test/java/Skeep/backend/weather/domain/locationGrid/LocationGridRepositoryTest.java
  src/test/java/Skeep/backend/weather/service/WeatherServiceTest.java
  src/test/java/Skeep/backend/weather/util/RegionUtilsTest.java
Labels: :sparkles: Feature

#133 (SKP-172) [Server] Tour API의 url을 변경한다
  src/main/java/Skeep/backend/location/tour/controller/TourController.java
Labels: 🔄 Refactor

#135 (SKP-173) [Server] GET API에 대해서 @RequestBody를 @RequestParam으로 변경한다
  src/main/java/Skeep/backend/location/tour/controller/TourController.java
  src/main/java/Skeep/backend/weather/controller/WeatherController.java
Labels: 🔄 Refactor
